### PR TITLE
ci.yml: bump flatpak builder to v6, image to gnome 44

### PR DESCRIPTION
**Pull request by kbdharun**

### CODE REVIEW

**Comment by SeaDve** [comment]
Thanks!

**Comment by kbdharun** [comment]
> Thanks!

Welcome 😄 , I noticed you guys have set up `actions-rs/toolchain@v1` in the workflow which hasn't been maintained for a while. So I would suggest using an alternative instead as the current one has node 12 is going to be deprecated soon.

**Comment by SeaDve** [comment]
> I noticed you guys have set up `actions-rs/toolchain@v1` in the workflow which hasn't been maintained for a while. So I would suggest using an alternative instead as the current one has node 12 is going to be deprecated soon.

Ah, I didn't knew that. Is `actions-rs/cargo@v1` the more recommended now?

**Comment by kbdharun** [comment]
> actions-rs/cargo@v1

I think all the actions in the org are unmaintained, I will check if there are any other alternative actions for rust or else you could set up build directly through a container in GitHub actions. I remember rnote doing it.

**Pull request merged**
